//TODO portrety seria zdjęć || photo from old laptop
import { imgArrayPhoto } from "../types";
import {
	ModelsFromŁódź,
	Cracow,
	warsaw01,
	Germany,
	Winter,
	Masuria,
	Staircase,
	Adisz,
	Studio01,
	Studio02,
	Cygary,
	Zakopane,
	Philocaly,
	Elevator,
	Rooftop,
	ShopConcrete,
	Ec1,
	Blocks,
	Solitude,
	Fade,
	Skyscraper,
	Łódź,
	Łódź01,
	Łódź02,
	Stanley,
	Mateusz,
	Studio,
	Hotel,
	Warsaw02,
	EgzodiaBlurry,
	NightDemon,
	Blurry,
	Philippines,
	PhilippineCouple,
	PhilippineLife,
	Philippine,
	Skate,
	StudioPhilippines,
	Nikola,
	PhilippineAnimals,
	PhilippineArchitecture,
	PhilippineModels01,
	PhilippineModels02,
	Bagio,
	NikMakino,
	Iga,
} from "./Photo";
import { PortfolioItem } from "./PortfolioItems";
export interface PhotoPortfolioItemsType extends Omit<PortfolioItem, "id"> {
	imgArray: imgArrayPhoto[];
	class?: string;
}
const PhotoPortfolioItems: PhotoPortfolioItemsType[] = [
	Adisz,
	Bagio,
	Blocks,
	Blurry,
	Cracow,
	Cygary,
	Ec1,
	EgzodiaBlurry,
	Elevator,
	Fade,
	Germany,
	Hotel,
	Łódź,
	Łódź01,
	Łódź02,
	Masuria,
	Mateusz,
	ModelsFromŁódź,
	NightDemon,
	NikMakino,
	Nikola,
	Philocaly,
	Philippine,
	PhilippineAnimals,
	PhilippineArchitecture,
	PhilippineModels01,
	PhilippineModels02,
	PhilippineCouple,
	PhilippineLife,
	Philippines,
	Rooftop,
	ShopConcrete,
	Skate,
	Skyscraper,
	Solitude,
	Staircase,
	Stanley,
	Studio,
	Studio01,
	Studio02,
	StudioPhilippines,
	warsaw01,
	Warsaw02,
	Winter,
	Zakopane,
	Iga,
];
export default PhotoPortfolioItems;
