import { PortfolioItem } from "./PortfolioItems";
export interface PhotoPortfolioItemsType extends Omit<PortfolioItem, "id"> {
	imgArray: string[];
}
const PhotoPortfolioItems: PhotoPortfolioItemsType[] = [
	{
		title: "studio01Title",
		description: "studio01description",
		imageCover: "/assets/img/portfolio/photo/studio01/05.webp",
		date: "2024-11-03",
		favorite: false,
		category: "CategoryPhotography",
		imgArray: [
			"/assets/img/portfolio/photo/studio01/01.webp",
			"/assets/img/portfolio/photo/studio01/02.webp",
			"/assets/img/portfolio/photo/studio01/03.webp",
			"/assets/img/portfolio/photo/studio01/04.webp",
			"/assets/img/portfolio/photo/studio01/05.webp",
			"/assets/img/portfolio/photo/studio01/06.webp",
			"/assets/img/portfolio/photo/studio01/07.webp",
			"/assets/img/portfolio/photo/studio01/08.webp",
			"/assets/img/portfolio/photo/studio01/09.webp",
			"/assets/img/portfolio/photo/studio01/10.webp",
			"/assets/img/portfolio/photo/studio01/11.webp",
			"/assets/img/portfolio/photo/studio01/12.webp",
			"/assets/img/portfolio/photo/studio01/13.webp",
			"/assets/img/portfolio/photo/studio01/14.webp",
			"/assets/img/portfolio/photo/studio01/15.webp",
			"/assets/img/portfolio/photo/studio01/16.webp",
			"/assets/img/portfolio/photo/studio01/17.webp",
			"/assets/img/portfolio/photo/studio01/18.webp",
			"/assets/img/portfolio/photo/studio01/19.webp",
			"/assets/img/portfolio/photo/studio01/20.webp",
			"/assets/img/portfolio/photo/studio01/21.webp",
			"/assets/img/portfolio/photo/studio01/22.webp",
			"/assets/img/portfolio/photo/studio01/23.webp",
			"/assets/img/portfolio/photo/studio01/24.webp",
			"/assets/img/portfolio/photo/studio01/25.webp",
			"/assets/img/portfolio/photo/studio01/26.webp",
			"/assets/img/portfolio/photo/studio01/27.webp",
			"/assets/img/portfolio/photo/studio01/28.webp",
			"/assets/img/portfolio/photo/studio01/29.webp",
			"/assets/img/portfolio/photo/studio01/30.webp",
			"/assets/img/portfolio/photo/studio01/31.webp",
			"/assets/img/portfolio/photo/studio01/32.webp",
			"/assets/img/portfolio/photo/studio01/33.webp",
			"/assets/img/portfolio/photo/studio01/34.webp",
			"/assets/img/portfolio/photo/studio01/35.webp",
			"/assets/img/portfolio/photo/studio01/36.webp",
			"/assets/img/portfolio/photo/studio01/37.webp",
			"/assets/img/portfolio/photo/studio01/38.webp",
			"/assets/img/portfolio/photo/studio01/39.webp",
			"/assets/img/portfolio/photo/studio01/40.webp",
			"/assets/img/portfolio/photo/studio01/41.webp",
			"/assets/img/portfolio/photo/studio01/42.webp",
			"/assets/img/portfolio/photo/studio01/43.webp",
			"/assets/img/portfolio/photo/studio01/44.webp",
			"/assets/img/portfolio/photo/studio01/45.webp",
			"/assets/img/portfolio/photo/studio01/46.webp",
			"/assets/img/portfolio/photo/studio01/47.webp",
			"/assets/img/portfolio/photo/studio01/48.webp",
			"/assets/img/portfolio/photo/studio01/49.webp",
			"/assets/img/portfolio/photo/studio01/50.webp",
		],
	},
	{
		title: "warsaw01Title",
		description: "warsaw01description",
		imageCover: "/assets/img/portfolio/photo/warsaw01/13.jpg",
		date: "2025-05-28",
		favorite: false,
		category: "CategoryPhotography",
		imgArray: [
			"/assets/img/portfolio/photo/warsaw01/01.jpg",
			"/assets/img/portfolio/photo/warsaw01/02.jpg",
			"/assets/img/portfolio/photo/warsaw01/03.jpg",
			"/assets/img/portfolio/photo/warsaw01/04.jpg",
			"/assets/img/portfolio/photo/warsaw01/05.jpg",
			"/assets/img/portfolio/photo/warsaw01/06.jpg",
			"/assets/img/portfolio/photo/warsaw01/07.jpg",
			"/assets/img/portfolio/photo/warsaw01/08.jpg",
			"/assets/img/portfolio/photo/warsaw01/09.jpg",
			"/assets/img/portfolio/photo/warsaw01/10.jpg",
			"/assets/img/portfolio/photo/warsaw01/11.jpg",
			"/assets/img/portfolio/photo/warsaw01/12.jpg",
			"/assets/img/portfolio/photo/warsaw01/13.jpg",
			"/assets/img/portfolio/photo/warsaw01/14.jpg",
			"/assets/img/portfolio/photo/warsaw01/15.jpg",
			"/assets/img/portfolio/photo/warsaw01/16.jpg",
			"/assets/img/portfolio/photo/warsaw01/17.jpg",
		],
	},
];
export default PhotoPortfolioItems;
