import { CategoryType } from "./const";

export interface PortfolioItem {
	id: number;
	title: string;
	description: string;
	image: string;
	date: string;
	favorite: boolean;
	category: CategoryType;
	techStack?: number[];
}
export const PortfolioItems: PortfolioItem[] = [
	{
		id: 1,
		title: "Project One",
		description: "Description of project one.",
		image: "/assets/img/portfolio/blank.jpg",
		date: "2023-01-01",
		favorite: false,
		category: "CategoryWebsite",
	},
	{
		id: 2,
		title: "Project Two",
		description: "Description of project two.",
		image: "/assets/img/portfolio/blank.jpg",
		date: "2023-02-01",
		favorite: true,
		category: "CategoryPhotography",
	},
	{
		id: 3,
		title: "Project Three",
		description: "Description of project three.",
		image: "/assets/img/portfolio/blank.jpg",
		date: "2023-03-01",
		favorite: false,
		category: "CategoryWebsite",
	},
	{
		id: 4,
		title: "Project Four",
		description: "Description of project four.",
		image: "/assets/img/portfolio/blank.jpg",
		date: "2023-04-01",
		favorite: true,
		category: "CategoryPhotography",
	},
	{
		id: 5,
		title: "Project Five",
		description: "Description of project five.",
		image: "/assets/img/portfolio/blank.jpg",
		date: "2023-05-01",
		favorite: false,
		category: "CategoryPhotography",
	},
	{
		id: 6,
		title: "Project Six",
		description: "Description of project six.",
		image: "/assets/img/portfolio/blank.jpg",
		date: "2023-06-01",
		favorite: true,
		category: "CategoryWebsite",
	},
	{
		id: 7,
		title: "Project Seven",
		description: "Description of project seven.",
		image: "/assets/img/portfolio/blank.jpg",
		date: "2023-07-01",
		favorite: false,
		category: "CategoryPhotography",
	},
	{
		id: 8,
		title: "Project Eight",
		description: "Description of project eight.",
		image: "/assets/img/portfolio/blank.jpg",
		date: "2023-08-01",
		favorite: true,
		category: "CategoryWebsite",
	},
	{
		id: 9,
		title: "Nature Gallery",
		description: "A collection of stunning nature photographs.",
		image: "/img/portfolio/nature.jpg",
		date: "2023-09-10",
		favorite: false,
		category: "CategoryPhotography",
	},
	{
		id: 10,
		title: "E-Commerce Platform",
		description: "A modern e-commerce website for online shopping.",
		image: "/img/portfolio/ecommerce.jpg",
		date: "2023-10-15",
		favorite: true,
		category: "CategoryWebsite",
	},
	{
		id: 11,
		title: "Urban Exploration",
		description: "Photography series exploring urban landscapes.",
		image: "/img/portfolio/urban.jpg",
		date: "2023-11-05",
		favorite: false,
		category: "CategoryPhotography",
	},
	{
		id: 12,
		title: "Portfolio Redesign",
		description: "A fresh redesign of my personal portfolio website.",
		image: "/img/portfolio/portfolio-redesign.jpg",
		date: "2023-12-01",
		favorite: true,
		category: "CategoryWebsite",
	},
	{
		id: 13,
		title: "Wildlife Wonders",
		description: "Capturing the beauty of wildlife in their natural habitat.",
		image: "/img/portfolio/wildlife.jpg",
		date: "2024-01-20",
		favorite: false,
		category: "CategoryPhotography",
	},
	{
		id: 14,
		title: "Startup Landing Page",
		description: "Landing page design for a tech startup.",
		image: "/img/portfolio/startup.jpg",
		date: "2024-02-10",
		favorite: true,
		category: "CategoryWebsite",
	},
	{
		id: 15,
		title: "Event Photography",
		description: "Memorable moments captured at various events.",
		image: "/img/portfolio/event.jpg",
		date: "2024-03-05",
		favorite: false,
		category: "CategoryPhotography",
	},
	{
		id: 16,
		title: "Blog Platform",
		description: "A feature-rich blogging platform for writers.",
		image: "/img/portfolio/blog.jpg",
		date: "2024-04-01",
		favorite: true,
		category: "CategoryWebsite",
		techStack: [1, 2, 3],
	},
];
export type PortfolioItemType = (typeof PortfolioItems)[number];
