export type TechCategory =
	| "Frontend"
	| "Backend"
	| "Database"
	| "Deployment"
	| "Tools";
export type TechStackBase = {
	id: number;
	name: string;
	type: "Framework" | "Language" | "Library" | "Tool" | "Others";
	category: TechCategory;
	docsUrl?: string;
	since: Date; // year of first use
	star?: boolean;
};
type TechStackWithClass = TechStackBase & {
	iconClass: string;
	iconImg?: never;
	darkIconImg?: never;
};
type TechStackWithImage = TechStackBase & {
	iconClass?: never;
	iconImg: string;
	darkIconImg?: string;
};
type TechStack = TechStackWithClass | TechStackWithImage;
export const TechStackArray: TechStack[] = [
	{
		id: 1,
		name: "HTML",
		type: "Language",
		category: "Frontend",
		since: new Date(2022, 0, 1),
		iconClass: "fi fi-brands-html5",
		docsUrl: "https://developer.mozilla.org/en-US/docs/Web/HTML",
		star: true,
	},
	{
		id: 2,
		name: "CSS",
		type: "Language",
		category: "Frontend",
		since: new Date(2022, 0, 1),
		iconClass: "fi fi-brands-css3",
		docsUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS",
		star: true,
	},
	{
		id: 3,
		name: "Scss/Sass",
		type: "Language",
		category: "Frontend",
		since: new Date(2023, 0, 1),
		iconClass: "fi fi-brands-sass",
		docsUrl: "https://sass-lang.com/documentation",
	},
	{
		id: 4,
		name: "JavaScript",
		type: "Language",
		category: "Frontend",
		since: new Date(2022, 0, 1),
		iconClass: "fi fi-brands-js",
		docsUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
		star: true,
	},
	{
		id: 5,
		name: "TypeScript",
		type: "Language",
		category: "Frontend",
		since: new Date(2025, 3, 1),
		iconClass: "fi fi-brands-typescript",
		docsUrl: "https://www.typescriptlang.org/docs/",
		star: true,
	},
	{
		id: 6,
		name: "React",
		type: "Framework",
		category: "Frontend",
		since: new Date(2024, 0, 1),
		iconImg: "/assets/icons/light/react-light.png",
		darkIconImg: "/assets/icons/dark/react-dark.png",
		docsUrl: "https://react.dev/",
		star: true,
	},
	{
		id: 7,
		name: "NextJs",
		type: "Framework",
		category: "Frontend",
		since: new Date(2025, 0, 1),
		iconImg: "/assets/icons/light/nextjs-light.png",
		darkIconImg: "/assets/icons/dark/nextjs-dark.png",
		docsUrl: "https://nextjs.org/docs",
		star: true,
	},
	{
		id: 8,
		name: "Tailwind CSS",
		type: "Framework",
		category: "Frontend",
		since: new Date(2023, 0, 1),
		iconImg: "/assets/icons/light/TailwindCssLight.png",
		darkIconImg: "/assets/icons/dark/TailwindCssDark.png",
		docsUrl: "https://tailwindcss.com/docs",
		star: true,
	},
	{
		id: 9,
		name: "Framer Motion",
		type: "Framework",
		category: "Frontend",
		since: new Date(2023, 0, 1),
		iconImg: "/assets/icons/light/framer-light.png",
		darkIconImg: "/assets/icons/dark/framer-dark.png",
		docsUrl: "https://www.framer.com/motion/",
	},
	{
		id: 10,
		name: "PHP",
		type: "Language",
		category: "Backend",
		since: new Date(2022, 0, 1),
		iconClass: "fi fi-brands-php",
		docsUrl: "https://www.php.net/docs.php",
		star: true,
	},
	{
		id: 11,
		name: "SQL",
		type: "Language",
		category: "Database",
		since: new Date(2022, 0, 1),
		iconClass: "fi fi-brands-mysql",
		docsUrl: "https://www.w3schools.com/sql/",
		star: true,
	},
	{
		id: 12,
		name: "NodeJs",
		type: "Framework",
		category: "Backend",
		since: new Date(2024, 0, 1),
		iconClass: "fi fi-brands-node-js",
		docsUrl: "https://nodejs.org/en/docs/",
		star: true,
	},
	{
		id: 13,
		name: "ExpressJs",
		type: "Framework",
		category: "Backend",
		since: new Date(2025, 0, 1),
		iconImg: "/assets/icons/light/expressjs-light.png",
		darkIconImg: "/assets/icons/dark/expressjs-dark.png",
		docsUrl: "https://expressjs.com/",
		star: true,
	},
	{
		id: 14,
		name: "Supabase",
		type: "Others",
		category: "Backend",
		since: new Date(2024, 0, 1),
		iconImg: "/assets/icons/light/supabase-light.png",
		darkIconImg: "/assets/icons/dark/supabase-dark.png",
		docsUrl: "https://supabase.com/docs",
		star: true,
	},
	{
		id: 15,
		name: "Vercel",
		type: "Others",
		category: "Deployment",
		since: new Date(2025, 0, 1),
		iconImg: "/assets/icons/light/vercel-light.png",
		darkIconImg: "/assets/icons/dark/vercel-dark.png",
		docsUrl: "https://vercel.com/docs",
	},
	{
		id: 16,
		name: "Cloudflare",
		type: "Others",
		category: "Deployment",
		since: new Date(2023, 0, 1),
		iconImg: "/assets/icons/light/Cloudflare-light.png",
		darkIconImg: "/assets/icons/dark/Cloudflare-dark.png",
		docsUrl: "https://developers.cloudflare.com/",
	},
	{
		id: 17,
		name: "Git",
		type: "Others",
		category: "Tools",
		since: new Date(2023, 0, 1),
		iconImg: "/assets/icons/light/Git-light.png",
		darkIconImg: "/assets/icons/dark/Git-dark.png",
		docsUrl: "https://git-scm.com/doc",
	},
	{
		id: 18,
		name: "GitHub",
		type: "Others",
		category: "Tools",
		since: new Date(2023, 2, 7),
		iconClass: "fi fi-brands-github",
		docsUrl: "https://docs.github.com/",
	},
	{
		id: 19,
		name: "ESLint",
		type: "Others",
		category: "Tools",
		since: new Date(2024, 0, 1),
		iconImg: "/assets/icons/light/Eslint-light.png",
		darkIconImg: "/assets/icons/dark/Eslint-dark.png",
		docsUrl: "https://eslint.org/docs/",
	},
	{
		id: 20,
		name: "Prettier",
		type: "Others",
		category: "Tools",
		since: new Date(2024, 0, 1),
		iconImg: "/assets/icons/light/prettier-light.png",
		darkIconImg: "/assets/icons/dark/prettier-dark.png",
		docsUrl: "https://prettier.io/docs/en/",
	},
	{
		id: 21,
		name: "Swiper",
		type: "Library",
		category: "Tools",
		since: new Date(2025, 5, 1),
		iconImg: "/assets/icons/light/swiper-light.png",
		darkIconImg: "/assets/icons/dark/swiper-dark.png",
		docsUrl: "https://swiperjs.com/react",
	},
	{
		id: 22,
		name: "React-Icons",
		type: "Library",
		category: "Tools",
		since: new Date(2024, 3, 1),
		iconImg: "/assets/icons/light/react-light.png",
		darkIconImg: "/assets/icons/dark/react-dark.png",
		docsUrl: "https://react-icons.github.io/react-icons/",
	},
	{
		id: 23,
		name: "HamburgerReact",
		type: "Library",
		category: "Tools",
		since: new Date(2025, 2, 1),
		iconClass: "fi fi-rr-hamburger",
		docsUrl: "https://hamburger-react.netlify.app/",
	},
	{
		id: 24,
		name: "Sonner",
		type: "Library",
		category: "Tools",
		since: new Date(2025, 8, 1),
		iconImg: "/assets/icons/light/react-light.png",
		darkIconImg: "/assets/icons/dark/react-dark.png",
		docsUrl: "https://sonner.emilkowal.ski/",
	},
	{
		id: 25,
		name: "EmailJS",
		type: "Library",
		category: "Tools",
		since: new Date(2025, 2, 1),
		iconImg: "/assets/icons/light/emailJs-light.png",
		darkIconImg: "/assets/icons/dark/emailJs-dark.png",
		docsUrl: "https://www.emailjs.com/docs/",
	},
	{
		id: 26,
		name: "i18n",
		type: "Library",
		category: "Tools",
		since: new Date(2025, 0, 1),
		iconClass: "fi fi-rr-language",
		docsUrl: "https://react.i18next.com/",
	},
	{
		id: 27,
		name: "Tailwind-Scrollbar",
		type: "Library",
		category: "Tools",
		since: new Date(2024, 2, 1),
		iconImg: "/assets/icons/light/TailwindCssLight.png",
		darkIconImg: "/assets/icons/dark/TailwindCssDark.png",
		docsUrl: "https://www.npmjs.com/package/tailwind-scrollbar",
	},
	{
		id: 28,
		name: "Docker",
		type: "Tool",
		category: "Tools",
		since: new Date(2025, 9, 1),
		iconClass: "fi fi-brands-docker",
		docsUrl: "https://www.docker.com/",
	},
	{
		id: 29,
		name: "Python",
		type: "Language",
		category: "Backend",
		since: new Date(2025, 8, 1),
		iconClass: "fi fi-brands-python",
		docsUrl: "https://www.python.org/doc/",
	},
	{
		id: 30,
		name: "Codacy",
		type: "Tool",
		category: "Tools",
		since: new Date(2025, 9, 1),
		iconClass: "fi fi-rr-shield-check",
		docsUrl: "https://docs.codacy.com/",
	},
	{
		id: 31,
		name: "jscpd",
		type: "Library",
		category: "Deployment",
		since: new Date(2025, 9, 1),
		iconClass: "fi fi-rr-search",
		docsUrl: "https://github.com/kucherenko/jscpd",
	},
	{
		id: 32,
		name: "c",
		type: "Library",
		category: "Backend",
		since: new Date(2025, 5, 1),
		iconClass: "fi fi-brands-c",
		docsUrl: "https://devdocs.io/c/",
	},
	{
		id: 33,
		name: "clsx",
		type: "Library",
		category: "Tools",
		since: new Date(2025, 2, 1),
		iconClass: "",
		docsUrl: "https://www.npmjs.com/package/clsx",
	},
	{
		id: 34,
		name: "twMerge",
		type: "Library",
		category: "Tools",
		since: new Date(2025, 2, 1),
		iconClass: "",
		docsUrl: "https://www.npmjs.com/package/tailwind-merge",
	},
	{
		id: 35,
		name: "JSON",
		type: "Language",
		category: "Database",
		since: new Date(2024, 1, 1),
		iconClass: "",
		docsUrl: "https://www.json.org/json-en.html",
	},
	{
		id: 36,
		name: "npm",
		type: "Tool",
		category: "Tools",
		since: new Date(2024, 1, 1),
		iconClass: "",
		docsUrl: "https://www.npmjs.com/",
	},
	{
		id: 37,
		name: "pnpm",
		type: "Tool",
		category: "Tools",
		since: new Date(2024, 1, 1),
		iconClass: "",
		docsUrl: "https://pnpm.io/",
	},
	{
		id: 38,
		name: "JEST",
		type: "Tool",
		category: "Tools",
		since: new Date(2025, 1, 1),
		iconClass: "",
		docsUrl: "https://jestjs.io/docs/getting-started",
	},
	{
		id: 39,
		name: "Sonar",
		type: "Tool",
		category: "Tools",
		since: new Date(2025, 1, 1),
		iconClass: "",
		docsUrl: "https://docs.sonarsource.com/",
	},
];
