import type { Metadata } from "next";
import { Kode_Mono } from "next/font/google";
import "./globals.css";

const geistMono = Kode_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${geistMono.className} antialiased text-foreground bg-background dark:bg-dark-background dark:text-dark-foreground transition-colors duration-300`}>
				{children}
			</body>
		</html>
	);
}
